### ISSUE TITLE
Remove the italic style from the about me text and put a beautiful font type

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#107]
**Describe the bug**
Now there is serif font style in the about me text

**To Reproduce**
1. Go to 'Yoshitha Site'
3. Scroll down to 'About Section'

**Expected behavior**
Remove the italic style from the about me text and put a beautiful font type

**Screenshots**

![image](https://user-images.githubusercontent.com/97069900/195982535-5ef16042-102b-497e-8ec0-7c2d3531cc5c.png)

**Are you working on it?**
No

**Comment by AlgyJr** [comment]
Hi @YoshithaRathnayake , I'd like to work on this.

**Comment by YoshithaRathnayake** [comment]
> 

Sure, go ahead @AlgyJr

**Comment by Kitashi14** [comment]
would like to complete this task

**Comment by NotAtitYet** [comment]
I would like to work on this issue. Please assign this to me.
