### ISSUE TITLE
Decrease the font weight of the about me description paragraph little bit more

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#110]
**Is your feature request related to a problem? Please describe.**
Currently, the font weight of the about me description paragraph is increased

**Describe the solution you'd like**
Decrease the font weight of the about me description paragraph little bit more

**Are you working on it?**
No

**Comment by rishabhknowss** [comment]
please assign me this issue

**Comment by YoshithaRathnayake** [comment]
> please assign me this issue

Sure, go ahead @

**Comment by charandevreddy** [comment]
hey @YoshithaRathnayake can you assign me?

**Comment by YoshithaRathnayake** [comment]
Sure, go ahead @charandevreddy

**Comment by Vishesh-Vijay** [comment]
please assign it to me

**Comment by YoshithaRathnayake** [comment]
> hey @YoshithaRathnayake can you assign me?

Are you working on this? shall I give this chance to another? @charandevreddy

**Comment by Keerthivardhan1** [comment]
can I work on this issue

**Comment by YoshithaRathnayake** [comment]
I'll work on this
