### ISSUE TITLE
`Clone your forked repository` section and description are sticked together

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#113]
**Describe the bug**
`Clone your forked repository` section and description are sticked together

**To Reproduce**
1. Go to 'Readme.md file'
3. Scroll down to 'Clone your forked repository'

**Expected behavior**
Click the end of the Clone your forked repository title and hit enter

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/197317393-43f6f74a-75b1-4114-aa1b-836aebf975c1.png)

**Are you working on it?**
No

**Comment by Arcturus22** [comment]
@YoshithaRathnayake 
I want to work on this Issue. Please assign me to this Issue.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I want to work on this Issue. Please assign me to this Issue.

Sure, go ahead @Arcturus22

**Comment by YoshithaRathnayake** [comment]
Do this also like what you did in my calculator website @Arcturus22
