### ISSUE TITLE
Add a beautiful scroll bar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#121]
Add a beautiful scroll bar

**Comment by william-monroy** [comment]
Hi @YoshithaRathnayake, could you assign me this issue?

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake, could you assign me this issue?

Sure, go ahead @william-monroy
