### ISSUE TITLE
Reduce the scroll bar width little bit

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#126]
Reduce the scroll bar width little bit

**Comment by YoshithaRathnayake** [comment]
I think @william-monroy you can work on this

**Comment by jusinamine** [comment]
assign me plz

**Comment by YoshithaRathnayake** [comment]
> assign me plz

Sure, go ahead @jusinamine

**Comment by jusinamine** [comment]
done. you can check the pull request
