### ISSUE TITLE
Add YAML logo to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#130]
Add YAML logo to the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198660646-1ca786c3-ae9e-4eb0-8fb6-1eb8d6a4b556.png)

**Comment by Zweak** [comment]
I'll work on it

**Comment by YoshithaRathnayake** [comment]
> I'll work on it

Sure, go ahead @Zweak
