### ISSUE TITLE
Use an `and` between the Bootstrap and Yaml in the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#132]
Use an `and` between the Boostrap and Yaml in the readme.md file

![image](https://user-images.githubusercontent.com/97069900/198676592-adfbdd2d-c822-4d26-b159-763bdf09963b.png)

**Comment by Georgezogos** [comment]
Hello, could you please asign it to me?

**Comment by YoshithaRathnayake** [comment]
> Hello, could you please asign it to me?

Sure, go ahead @Georgezogos
