### ISSUE TITLE
Add contact form in the contact section

### ISSUE THREAD

**Issue by ankitbajpai65** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#140]
Hello @YoshithaRathnayake, I want to add the contact form into the contact section of the website. Please assign me this issue so that I can work on that.
Thanks!

**Comment by YoshithaRathnayake** [comment]
> Hello @YoshithaRathnayake, I want to add the contact form into the contact section of the website. Please assign me this issue so that I can work on that. Thanks!

sure go ahead @ankitbajpai65

**Comment by ankitbajpai65** [comment]
Hello @YoshithaRathnayake, I have performed all the changes as discussed above in PR #142. 
Have a look!

**Comment by YoshithaRathnayake** [comment]
> Hello @YoshithaRathnayake, I have performed all the changes as discussed above in PR #142. Have a look!

Did you complete hacktoberfest @ankitbajpai65
