### ISSUE TITLE
Reduce the font size little bit in the contact section text

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#144]
Currently, the text in the contact section font size is increased. Reduce the font size little bit in the contact section text

**Comment by abitsalihu** [comment]
Hey @YoshithaRathnayake, I would like to help with this issue. :)

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake, I would like to help with this issue. :)

Sure, go ahead @abitsalihu

**Comment by abitsalihu** [comment]
@YoshithaRathnayake I would also like to change the font color because the current color is really hard to read with that background!

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I would also like to change the font color because the current color is really hard to read with that background!

In what?

**Comment by abitsalihu** [comment]
<img width="1440" alt="Screen Shot 2022-11-01 at 12 25 43" src="https://user-images.githubusercontent.com/94648837/199222710-a635c4da-a133-4531-a4fc-5b7e57a06b34.png">

The font color is really hard to read, so should I change the color too or just the font size?

**Comment by abitsalihu** [comment]
@YoshithaRathnayake Alright. :)

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Alright. :)

Did you complete the hacktoberfest 2022 @abitsalihu

**Comment by abitsalihu** [comment]
@YoshithaRathnayake I did finish it, wbu? And also are you on linkedIn?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I did finish it, wbu? And also are you on linkedIn?

Yes https://www.linkedin.com/in/yoshitha-rathnayake

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I did finish it, wbu? And also are you on linkedIn?

Send me the pr @abitsalihu

**Comment by abitsalihu** [comment]
@YoshithaRathnayake I did send it, you just need to merge it?

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I did send it, you just need to merge it?

Merged! @abitsalihu

**Comment by abitsalihu** [comment]
@YoshithaRathnayake Thank you. :)
