### ISSUE TITLE
The gap between the email and the text is very poor in the contact text

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#153]
- The gap between the email and the text is very poor in the contact text
- Add a padding or margin to increase the gap

![image](https://user-images.githubusercontent.com/97069900/206857804-2b43ac31-91f3-4793-9d3d-b6271a4bdd7a.png)

**Comment by Rishav1707** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure
