### ISSUE TITLE
Remove the unwanted link tag in the contact section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#154]
- Currently, there is an unwanted link tag in the contact section
- Remove it

https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/bbb62296bd27270313436aa40de85fb2fb471136/dark/index.html#L234-L235

**Comment by Rishav1707** [comment]
Shall I work on this?

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this?

Sure
