### ISSUE TITLE
Remove the `Elfsight Apps` script tag from index.html file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#161]
Remove the `Elfsight Apps` script tag from index.html file

https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/a71b7d512553edaed7a6a84530445322f9a81f09/index.html#L121-L123

**Comment by Rishav1707** [comment]
Shall I work on this issue? @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this issue? @YoshithaRathnayake

Sure
