### ISSUE TITLE
Contact section main heading background shadow is missing

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#164]
- Currently, the contact section main heading background shadow is missing
- Add this code,
````html
 <!-- Contact Section --> 
 <section id="contact"> 
   <h1>CONTACT ME</h1>
   <h3>CONTACT <span class="text-info">ME</span></h3> 
````
- To here in the contact section.
https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/blob/a71b7d512553edaed7a6a84530445322f9a81f09/dark/index.html#L211-L213

**Comment by maddy020** [comment]
Please assign this issue to me
I have resolved it and going to create a PR
