### ISSUE TITLE
Change the telegram icon in the social media icons

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#166]
- Currently, the telegram icon inserted is wrong
- Add the new telegram icon `https://img.icons8.com/fluency/48/telegram-app.png`

![image](https://user-images.githubusercontent.com/97069900/206943624-83e3cd2e-8b79-43ff-bb6b-6c98d17f0b44.png)

**Comment by maddy020** [comment]
Please assign this issue to me

**Comment by YoshithaRathnayake** [comment]
> Please assign this issue to me

Sure

**Comment by maddy020** [comment]
I have already created a PR 
Please review and help in merging that PR
