### ISSUE TITLE
The instagram icon is not loading in the social media icons

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#167]
- Currently, the instagram icon is not loading in the social media icons
- Add the correct icon `https://img.icons8.com/fluency/48/instagram-new.png`

![image](https://user-images.githubusercontent.com/97069900/206943837-7b34b413-6f6b-42d9-b776-1c5bde85f142.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?? @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this issue?? @YoshithaRathnayake

Sure
