### ISSUE TITLE
The github icon is not loading in the social media icons

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#168]
- Currently, the github icon is not loading in the social media icons
- Add the correct icon `https://img.icons8.com/ios-glyphs/48/github.png`

![image](https://user-images.githubusercontent.com/97069900/206943967-432e4bda-8764-456d-8821-7a38270c4f41.png)

**Comment by maddy020** [comment]
Please assign this issue to me

**Comment by Rishav1707** [comment]
Shall I work on this issue?? @YoshithaRathnayake

**Comment by YoshithaRathnayake** [comment]
> Shall I work on this issue?? @YoshithaRathnayake

Sure
