### ISSUE TITLE
The github icon is transparent in the social media icons

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#178]
- Currently, the github icon is transparent in the social media icons
- Add this icon again,

`https://img.icons8.com/ios-glyphs/48/github.png`

![image](https://user-images.githubusercontent.com/97069900/207324710-9d3cbcdd-624a-4156-8f8c-e6875fd9a957.png)

**Comment by Rishav1707** [comment]
![Screenshot 2022-12-13 192224](https://user-images.githubusercontent.com/97666287/207347550-b2a4edd4-a2be-46dc-a1f5-50357be9f9d7.png)
After adding this icon again, no changes happen.
Both the png are transparent.

**Comment by YoshithaRathnayake** [comment]
> ![Screenshot 2022-12-13 192224](https://user-images.githubusercontent.com/97666287/207347550-b2a4edd4-a2be-46dc-a1f5-50357be9f9d7.png) After adding this icon again, no changes happen. Both the png are transparent.

Oh ok then we will use a new icon @Rishav1707

**Comment by Rishav1707** [comment]
OK @YoshithaRathnayake
