### ISSUE TITLE
Create a feature request to introduce new features

### ISSUE THREAD

**Issue by priyankarpal** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#208]
**Hey! I have checked your website. Your website is good but I think you need to add some sections such as projects, tech stack, journey, logo etc.**

**Also you need to center your social icons for better looks**

![Screenshot from 2023-01-07 21-13-08](https://user-images.githubusercontent.com/88102392/211158886-526357b3-8f4c-4e9b-a853-60cf8f30c51a.png)

**Comment by YoshithaRathnayake** [comment]
You can work on this @priyankarpal

**Comment by priyankarpal** [comment]
Done. Check
