### ISSUE TITLE
Change the twitter (X) link in the social media icons section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#222]
**Is your feature request related to a problem? Please describe.**
Currently, the link in the twitter (X) icon is wrong

**Describe the solution you'd like**
Change the twitter (X) link in the social media icons section

New link - https://x.com/Yoshitha_R

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by chow870** [comment]
I am interested to work on this issue. Plz assign it to me

**Comment by YoshithaRathnayake** [comment]
> I am interested to work on this issue. Plz assign it to me

So you get assigned for another issue right?

**Comment by chow870** [comment]
yes, this one is different. assign me for this

**Comment by YoshithaRathnayake** [comment]
> yes, this one is different. assign me for this

So if someone else commented in this issue I will assign it for him/her, bcs you already did one noh? @chow870

**Comment by S-125** [comment]
Please assign me this

**Comment by YoshithaRathnayake** [comment]
> Please assign me this

Sure! @S-125 

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by S-125** [comment]
@YoshithaRathnayake I have made a PR please review it and please add hacktoberfest-accepted label before merging it as I have already faced an issue in which the maintainer forgot to add the label.
