### ISSUE TITLE
The twitter (X) icon is not updated

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#223]
**Is your feature request related to a problem? Please describe.**
Currently, there is the old twitter logo in the social media icons section. It should be updated to the new X logo

**Describe the solution you'd like**
Add the new X (twitter) logo to the social media icons section

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository

# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by Shivansh-22866** [comment]
Assign me

**Comment by YoshithaRathnayake** [comment]
> Assign me

Sure! @Shivansh-22866 

# Don't forget to star the repository

**Comment by Shivansh-22866** [comment]
This icon will work for the new X logo?
![Screenshot_20241006_193825](https://github.com/user-attachments/assets/c2a7e1d1-8dda-4274-b444-08ce424781a8)

**Comment by Shivansh-22866** [comment]
Otherwise I have another icon as well. Should I proceed with this one?
![Screenshot_20241006_194229](https://github.com/user-attachments/assets/89d827ff-4454-4b38-bdaa-c7f12ea80758)

**Comment by YoshithaRathnayake** [comment]
> This icon will work for the new X logo? ![Screenshot_20241006_193825](https://private-user-images.githubusercontent.com/131197200/373953202-c2a7e1d1-8dda-4274-b444-08ce424781a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjQyMTksIm5iZiI6MTcyODIyMzkxOSwicGF0aCI6Ii8xMzExOTcyMDAvMzczOTUzMjAyLWMyYTdlMWQxLThkZGEtNDI3NC1iNDQ0LTA4Y2U0MjQ3ODFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNDExNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWU3MDczMTk4MjcwZmQ0OTIzMzkxYjU1NTdiZDU2ODYwNmM5YmI4MmVkZmI5ZDkzYWM0MmQ2M2I2NDE4MjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wIdnqiN0yN3yHeCwweTRpWFJJseQM_Lpmv3DOjxs2qE)

what do you mean @Shivansh-22866 and also can you find an icon from icons8 with background white (The letter X should be white otherwise it will be transparent)

**Comment by YoshithaRathnayake** [comment]
> Otherwise I have another icon as well. Should I proceed with this one? ![Screenshot_20241006_194229](https://private-user-images.githubusercontent.com/131197200/373953458-89d827ff-4454-4b38-bdaa-c7f12ea80758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjQyNzcsIm5iZiI6MTcyODIyMzk3NywicGF0aCI6Ii8xMzExOTcyMDAvMzczOTUzNDU4LTg5ZDgyN2ZmLTQ0NTQtNGIzOC1iZGFhLWM3ZjEyZWE4MDc1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNDEyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDExNDUzMjZjZDljNDRmYTYyNzk1ZTc4NGI2ZGI0YWQ3YzQ4OTQ2NzdjYzA2ODJlN2JkYTk1N2E4Njk3N2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pqf5G5ULqiOy96EThFmPqydA0r8QwaP8CbmY0UfyIVk)

Ah nice @Shivansh-22866 you can continue with this logo

**Comment by Shivansh-22866** [comment]
I will send a PR with the white Twitter(X) logo then? Is that fine?

**Comment by YoshithaRathnayake** [comment]
> I will send a PR with the white Twitter(X) logo then? Is that fine?

Yeah it's fine @Shivansh-22866

**Comment by Shivansh-22866** [comment]
In case you have received and reviewed the PR, merge it kindly @YoshithaRathnayake
