### ISSUE TITLE
Change the LinkedIn profile link in the social media icons section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#224]
**Is your feature request related to a problem? Please describe.**
Currently, the link in the LinkedIn icon is wrong

**Describe the solution you'd like**
Change the LinkedIn profile link in the social media icons section

New link - https://www.linkedin.com/in/yoshitharathnayake/

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by Sriparno08** [comment]
Hey @YoshithaRathnayake, i would like to work on this issue.

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake, i would like to work on this issue.

Sure @Sriparno08 

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)
