### ISSUE TITLE
Change the instagram profile link in the social media icons section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#225]
**Is your feature request related to a problem? Please describe.**
Currently, the link in the instagram icon is wrong

**Describe the solution you'd like**
Change the instagram profile link in the social media icons section

New link - https://www.instagram.com/_yoshitha.r_/

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by chow870** [comment]
I am interested, could you assign it to me.

**Comment by YoshithaRathnayake** [comment]
> I am interested, could you assign it to me.

Sure @chow870 

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)
