### ISSUE TITLE
Make the medium logo in the social media icons to open in another window

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#226]
**Is your feature request related to a problem? Please describe.**
Currently, the the link of the medium icon is opening in the same window

**Describe the solution you'd like**
Make the medium logo in the social media icons to open in another window

Add this tag for the `<a href="">` attribute

`
target="_blank"
`

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by dexterousdhruv** [comment]
Could you please assign me this task? I would really appreciate the opportunity.

**Comment by YoshithaRathnayake** [comment]
> Could you please assign me this task? I would really appreciate the opportunity.

Sure! @dexterousdhruv 

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by dexterousdhruv** [comment]
@YoshithaRathnayake  Kindly review the PR.
