### ISSUE TITLE
Change the YouTube Channel link in the social media icons section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#227]
**Is your feature request related to a problem? Please describe.**
Currently, the link in the youtube icon is wrong

**Describe the solution you'd like**
Change the YouTube channel link in the social media icons section

New link - https://www.youtube.com/@YoshithaRathnayake

**Are you working on it?**
No (The first one who comment on this issue will be assigned)

# Don't forget to star the repository
# Don't forget to subscribe my YouTube channel also - https://www.youtube.com/@YoshithaRathnayake
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by Virus2466** [comment]
hello , can I work on this issue ?

**Comment by YoshithaRathnayake** [comment]
> hello , can I work on this issue ?

Yeah sure @Virus2466 
Your username? 😂😂😂 Are you a virus no right? Hope you are not a virus 🤣
