### ISSUE TITLE
Center the social media icons

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#241]
**Is your feature request related to a problem? Please describe.**
Currently, the social media icons are not centered

**Describe the solution you'd like**
Center the social media icons

**Are you working on it?**
No

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by YoshithaRathnayake** [comment]
@Ishaan0132 comment on this issue, then I can assign you

# Don't forget to star the repository
# Don't forget to follow me on social media (Visit my GitHub profile for more info)

**Comment by Ishaan0132** [comment]
Already created a PR for this issue.
