### ISSUE TITLE
I don't know

### ISSUE THREAD

**Issue by AliReza1083** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#70]
Can you tell how should I collaborate with you with this project?
what should I do?

**Comment by YoshithaRathnayake** [comment]
Still this not done! I will tell after I create this

**Comment by AliReza1083** [comment]
Then, what is the point of OPEN-Source?

**Comment by YoshithaRathnayake** [comment]
> Then, what is the point of OPEN-Source?

That's true but I didn't finish this project
