### ISSUE TITLE
Change the about me description

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#71]
**Is your feature request related to a problem? Please describe.**
Currently, there is a lorem ipsum tag for the about me description

**Describe the solution you'd like**
Change it like this "     Hi, I am **_Yoshitha Rathnayake_**. I am a student and I am 14 years old. I live in **_Kandy_** in **_Sri Lanka_**. I am studing in **_St.Anthony's College Kandy_**. Now, I am in Grade 9D in my school. This is my First Web Site. My favourite subject is **_Information and Communication Technology_**. My mother's name is **_Sudeshika Manthilake_** and my father's name is **_Athula Rathnayake_**. I hope to be a Computer Engineer in the future.     "

**Are you working on it?**
No

**Comment by jsvigneshkanna** [comment]
Hi @YoshithaRathnayake , please assign this to my name

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake , please assign this to my name

sure go ahead

**Comment by YoshithaRathnayake** [comment]
> Hi @YoshithaRathnayake , please assign this to my name

If you have any bug seen in my website pls let me know

**Comment by YoshithaRathnayake** [comment]
And don't forget to follow me @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
Have raised new PR: #72 , please check the code and merge them
Please add `hactoberfest-accepted` label, so that I can keep track my contributions this month

**Comment by YoshithaRathnayake** [comment]
> Have raised new PR: #72 , please check the code and merge them Please add `hactoberfest-accepted` label, so that I can keep track my contributions this month

sure
