### ISSUE TITLE
Align the about me paragraph with the image

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#73]
**Describe the bug**
Currently, the paragraph is aligned to down when compare with the image

**To Reproduce**
1. Go to 'WEBSITE'
3. Scroll down to 'About Section'

**Expected behavior**
Align it with the image

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/194759270-c754ffbf-fbb0-4154-bec9-60afe193c3a7.png)

**Are you working on it?**
No

**Comment by mb-008** [comment]
i want to work on this issue

**Comment by YoshithaRathnayake** [comment]
> i want to work on this issue

sure go ahead

**Comment by mb-008** [comment]
[improved alignment.docx](https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/files/9741715/improved.alignment.docx)
Is this allgnment fine?

**Comment by YoshithaRathnayake** [comment]
Yeah it's good take it little bit down so it will be like centered when compare with the image
