### ISSUE TITLE
Change the font type to a good font type in about me description in About Me Section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#75]
**Is your feature request related to a problem? Please describe.**
Currently, the font type is not pretty in the about me description at About Me Section

**Describe the solution you'd like**
Change the font type to a good font type in about me description in About Me Section

**Are you working on it?**
No

**Comment by Amank-root** [comment]
Hi, @YoshithaRathnayake can you please assign it to me?

**Comment by shrutilenka** [comment]
Hey @YoshithaRathnayake ,I am interested to work on this Issue,could you please assign this to me?

**Comment by YoshithaRathnayake** [comment]
Assigned @Amank-root

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake ,I am interested to work on this Issue,could you please assign this to me?

Do #76
