### ISSUE TITLE
Change my age to 14 in the meta tag descriptions

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#76]
**Is your feature request related to a problem? Please describe.**
Currently, my age on meta tag descriptions on index.html file is still 13 years

**Describe the solution you'd like**
Change my age to 14 in the meta tag descriptions in index.html file

**Are you working on it?**
No

**Comment by dheephiga** [comment]
Could you assign this to me?

**Comment by Hemang-05** [comment]
i will do it

**Comment by YoshithaRathnayake** [comment]
Sure, go ahead @Hemang-05

**Comment by Hiresh23** [comment]
i would like to contribute

**Comment by muskaan04** [comment]
i would like to work on this?

**Comment by YoshithaRathnayake** [comment]
> i would like to work on this?

#87 do this @muskaan04

**Comment by YoshithaRathnayake** [comment]
@AlgyJr can you do this?

**Comment by Keerthivardhan1** [comment]
is this issue is open .i  would like to work on this

**Comment by YoshithaRathnayake** [comment]
> is this issue is open .i would like to work on this

Yes there are some issues of my year update them

**Comment by YoshithaRathnayake** [comment]
Assigned @Keerthivardhan1

**Comment by Tanucode** [comment]
may i contribute to this?

**Comment by Keerthivardhan1** [comment]
age is updated in all the index.html files
