### ISSUE TITLE
Remove the parents' names from about me description

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#83]
**Is your feature request related to a problem? Please describe.**
Currently, there are parents' names in about me description

**Describe the solution you'd like**
Remove them bcs using them is unsecure

**Are you working on it?**
No

**Comment by aashish-1904** [comment]
i would like to work on this

**Comment by YoshithaRathnayake** [comment]
> i would like to work on this

Sure, go ahead @aashish-1904

**Comment by YoshithaRathnayake** [comment]
Please do this also @AlgyJr

**Comment by YoshithaRathnayake** [comment]
I'll work on this
