### ISSUE TITLE
Add a sentence to contact section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#84]
**Is your feature request related to a problem? Please describe.**
Now the contact section is empty

**Describe the solution you'd like**
Add a sentence to contact section as "Contact me via Email, Message or connect me with social media accounts. Also send me any inquiries by filling in the form given just below."

**Are you working on it?**
No

**Comment by Hiresh23** [comment]
can i work on this issue please assign it to me

**Comment by YoshithaRathnayake** [comment]
> can i work on this issue please assign it to me

Sure, go ahead @Hiresh23

**Comment by Hiresh23** [comment]
can you send me your mail for attaching  in form

**Comment by Hiresh23** [comment]
i have made few changes to contact page and top font if you want anything new do tell

**Comment by theotsuaneng** [comment]
hi @YoshithaRathnayake can I be assigned this issue

**Comment by YoshithaRathnayake** [comment]
Sure, go ahead @theotsuaneng

**Comment by theotsuaneng** [comment]
Hi @YoshithaRathnayake may you please accept my pull #120
