### ISSUE TITLE
Add my email to the contact section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#86]
**Is your feature request related to a problem? Please describe.**
Currently, there is no email in contact section

**Describe the solution you'd like**
Add the email icon and put like this "Email (Personal) : yoshithasbrathnayake@gmail.com"

**Are you working on it?**
No

**Comment by Mercysticks** [comment]
I want to add the email icon. Can I do this?

**Comment by YoshithaRathnayake** [comment]
> I want to add the email icon. Can I do this?

Sure, go ahead @Mercysticks

**Comment by Mercysticks** [comment]
@YoshithaRathnayake I already created a PR.

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I already created a PR.

Changes requested @Mercysticks

**Comment by muskaan04** [comment]
i would like to work on this?

**Comment by muskaan04** [comment]
i would like to work on this?

**Comment by Mercysticks** [comment]
Please @muskaan04 I've been assigned to it and I have already submitted a PR. And I'm already working on the changes. If you don't mind please you could find some other issues to work on. thank you

**Comment by YoshithaRathnayake** [comment]
Can you work on this @jsvigneshkanna really sorry for the inconvenience caused, I won't put spam for you again so please work on this...

**Comment by jsvigneshkanna** [comment]
@YoshithaRathnayake 
Sure will fix it

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake Sure will fix it

Go ahead @jsvigneshkanna

**Comment by theotsuaneng** [comment]
hi @YoshithaRathnayake can I be assigned this issue

**Comment by muskaan04** [comment]
hi, can I work on this?

**Comment by YoshithaRathnayake** [comment]
> hi, can I work on this?

sure but the one who has put the pr first will be accepted and merged @theotsuaneng @muskaan04

**Comment by Mercysticks** [comment]
@YoshithaRathnayake I made a Pull Request to this issue. Please Review.

**Comment by muskaan04** [comment]
Thankyou
