### ISSUE TITLE
Add my education details to the contact section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#88]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't about my education in contact section

**Describe the solution you'd like**
Add a education icon and put like this "Education : St. Anthony's College, Kandy"

**Are you working on it?**
No

**Comment by jsvigneshkanna** [comment]
Please assign this to my, will work on it

**Comment by real-zit** [comment]
Please assign this to my, will work on it

**Comment by YoshithaRathnayake** [comment]
> Please assign this to my, will work on it

Sure, go ahead @real-zit

**Comment by muskaan04** [comment]
i would like to work on this?
