### ISSUE TITLE
Link the contact section to the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [YoshithaRathnayake/NEW-YOSHITHA-WEBSITE#90]
**Is your feature request related to a problem? Please describe.**
Currently, the contact section is not linked to the navbar

**Describe the solution you'd like**
Link the contact section to the nav-item contact in the navbar

**Are you working on it?**
No

**Comment by jsvigneshkanna** [comment]
Please assign this to my, will work on it

**Comment by YoshithaRathnayake** [comment]
> Please assign this to my, will work on it

Sure, go ahead @jsvigneshkanna

**Comment by Hiresh23** [comment]
can i please work on this , assign it to me
